#!/usr/bin/env bash
set -euo pipefail

# Mojang 公式の ja_jp.json から、Discord 通知に使う進捗タイトルと説明を更新する
#
# 実行方法
#   ./scripts/update-advancement-translations.sh
#   ./scripts/update-advancement-translations.sh 26.1.2

root_dir="$(cd "$(dirname "$0")/.." && pwd)"
compose_file="${MINECRAFT_COMPOSE_FILE:-$root_dir/compose.yml}"
output_file="${ADVANCEMENT_TRANSLATIONS_FILE:-$root_dir/custom-plugins/DiscordGuildGate/src/main/resources/advancements-ja_jp.properties}"
version_manifest_url="${MINECRAFT_VERSION_MANIFEST_URL:-https://piston-meta.mojang.com/mc/game/version_manifest_v2.json}"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1" >&2
    exit 2
  fi
}

sha1_file() {
  if command -v sha1sum >/dev/null 2>&1; then
    sha1sum "$1" | awk '{print $1}'
  else
    shasum -a 1 "$1" | awk '{print $1}'
  fi
}

download() {
  curl -fsS \
    -H "User-Agent: densanken-mc-setup/1.0 (advancement translation update)" \
    -o "$2" \
    "$1"
}

require_mojang_metadata_url() {
  case "$1" in
    https://piston-meta.mojang.com/*) ;;
    *)
      echo "ERROR: Mojang 以外の metadata URL は使用できません: $1" >&2
      exit 1
      ;;
  esac
}

need curl
need jq
need perl

current_version="$(perl -ne 'print $1 if /^\s*VERSION:\s*"([^"]+)"/' "$compose_file")"
version="${1:-$current_version}"
if [[ ! "$version" =~ ^[0-9][0-9A-Za-z._-]*$ ]]; then
  echo "ERROR: Minecraft version の形式が不正です: $version" >&2
  exit 2
fi

work_dir="$(mktemp -d)"
output_temporary="$(mktemp "$output_file.next.XXXXXX")"
cleanup() {
  rm -rf -- "$work_dir"
  rm -f -- "$output_temporary"
}
trap cleanup EXIT HUP INT TERM

version_manifest="$work_dir/version-manifest.json"
version_metadata="$work_dir/version.json"
asset_index="$work_dir/assets.json"
language_file="$work_dir/ja_jp.json"

download "$version_manifest_url" "$version_manifest"
version_row="$(jq -r --arg version "$version" '
  .versions[] | select(.id == $version) | [.url, .sha1] | @tsv
' "$version_manifest")"
IFS=$'\t' read -r version_url version_sha1 <<<"$version_row"
if [[ ! "${version_sha1:-}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "ERROR: Minecraft $version の公式 metadata が見つかりません" >&2
  exit 1
fi
require_mojang_metadata_url "$version_url"

download "$version_url" "$version_metadata"
if [ "$(sha1_file "$version_metadata")" != "$version_sha1" ]; then
  echo "ERROR: Minecraft version metadata の SHA-1 が一致しません" >&2
  exit 1
fi

asset_index_url="$(jq -r '.assetIndex.url // empty' "$version_metadata")"
asset_index_sha1="$(jq -r '.assetIndex.sha1 // empty' "$version_metadata")"
if [[ ! "$asset_index_sha1" =~ ^[0-9a-f]{40}$ ]]; then
  echo "ERROR: asset index の情報を取得できません" >&2
  exit 1
fi
require_mojang_metadata_url "$asset_index_url"

download "$asset_index_url" "$asset_index"
if [ "$(sha1_file "$asset_index")" != "$asset_index_sha1" ]; then
  echo "ERROR: asset index の SHA-1 が一致しません" >&2
  exit 1
fi

language_hash="$(jq -r '.objects["minecraft/lang/ja_jp.json"].hash // empty' "$asset_index")"
language_size="$(jq -r '.objects["minecraft/lang/ja_jp.json"].size // empty' "$asset_index")"
if [[ ! "$language_hash" =~ ^[0-9a-f]{40}$ ]] || [[ ! "$language_size" =~ ^[0-9]+$ ]]; then
  echo "ERROR: ja_jp.json の asset 情報を取得できません" >&2
  exit 1
fi

language_url="https://resources.download.minecraft.net/${language_hash:0:2}/$language_hash"
download "$language_url" "$language_file"
if [ "$(sha1_file "$language_file")" != "$language_hash" ] || \
   [ "$(wc -c < "$language_file" | tr -d ' ')" != "$language_size" ]; then
  echo "ERROR: ja_jp.json の hash または size が一致しません" >&2
  exit 1
fi

if ! jq -e '
  .["advancements.story.mine_stone.title"] == "石器時代" and
  (.["advancements.story.mine_stone.description"] | type == "string") and
  ([to_entries[] |
    select(.key | startswith("advancements.")) |
    select(.key | test("\\.(title|description)$"))] | length > 0) and
  all(to_entries[] |
    select(.key | startswith("advancements.")) |
    select(.key | test("\\.(title|description)$"));
    (.key | test("^[a-z0-9_.-]+$")) and
    (.value | type == "string") and
    (.value | test("^[[:space:]]") | not))
' "$language_file" >/dev/null; then
  echo "ERROR: ja_jp.json の進捗タイトルと説明を安全な properties 形式へ変換できません" >&2
  exit 1
fi

{
  printf '# Generated by scripts/update-advancement-translations.sh\n'
  printf '# Minecraft version: %s\n' "$version"
  printf '# ja_jp.json SHA-1: %s\n' "$language_hash"
  jq -r '
    to_entries |
    map(select(.key | startswith("advancements."))) |
    map(select(.key | test("\\.(title|description)$"))) |
    sort_by(.key)[] |
    .value |= (
      gsub("\\\\"; "\\\\") |
      gsub("\\r"; "\\r") |
      gsub("\\n"; "\\n") |
      gsub("\\t"; "\\t")
    ) |
    "\(.key)=\(.value)"
  ' "$language_file"
} > "$output_temporary"
chmod 0644 "$output_temporary"

if [ -f "$output_file" ] && cmp -s "$output_temporary" "$output_file"; then
  echo "OK: 進捗の日本語辞書は更新済みです: Minecraft $version"
  exit 0
fi

mv "$output_temporary" "$output_file"
output_temporary=""
echo "OK: 進捗の日本語辞書を更新しました: Minecraft $version"
echo "次の手順: ./scripts/update-discord-guild-gate-lock.sh"
